### ISSUE TITLE
TripalPanes disabled by default?

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#117]
After migrating content from nodes to entities, it seems all TripalPanes are disabled by default for some content types (analysis, mRNA,gene but not organism, supercontig). This results in a page with a table of contents on the left and no panes on the right. The table of contents includes appropriate links (ie: Summary, Properties, etc.) but clicking on them does nothing. Manually dragging them into the Right column in "Manage Display" Fixes the problem but I feel like this would be unexpected behaviour to a site admin.

@shawnawsu do you have any ideas what is causing this?

## Background
I'm testing the upgrade process of a basic Tripal 2 site to Tripal 3. Completing the entire upgrade process with Tripal 3 dev (3df04d61728ae8527db892def40d3479cb6a8e78) or Tripal 3 dev (7a223166fb2dcb26b67cd2e695c530194f694b5b) produces the same behaviour. PS. I tried the full upgrade without the last commit because it was a "Fix" on my part to the prepare code related to the DS module. I wanted to confirm the problem wasn't my fix and the fact I see it in both cases proves that to me.

## Screenshot: Analysis Page
![screen shot 2017-06-05 at 4 03 00 pm](https://cloud.githubusercontent.com/assets/1566301/26805441/278c1c8a-4a09-11e7-86c9-69747a8cfbca.png)
## Screenshot: Analysis "Manage Display"
![screen shot 2017-06-05 at 4 02 47 pm](https://cloud.githubusercontent.com/assets/1566301/26805440/278b2f3c-4a09-11e7-866a-1ac6605cc6ed.png)

**Comment by shawnawsu** [comment]
I've encountered this before, I must have introduced the problem when I started processing for alpha order. I will dig into this now.

**Comment by shawnawsu** [comment]
@laceysanderson Can you just confirm which tripal 7.x-3.x (drupal.org beta/alpha or a pull from github) you were using or when you last pulled before this? I notice your fields are not in alpha order (Relationship, Summary, Name) and need to know if I need to look at that as well.

**Comment by laceysanderson** [comment]
Looks like I was on 3df04d61728ae8527db892def40d3479cb6a8e78. I just rebuilt a generic tripal3 site (79fb833f642c0d7f1fb7d36243a32bc5cd14a476) and see the following order for the Map content type:
![screen shot 2017-06-07 at 2 26 44 pm](https://user-images.githubusercontent.com/1566301/26899788-699dff96-4b8d-11e7-9ada-71f34867bccc.png)

**Comment by shawnawsu** [comment]
I cannot get this error to occur on my installations (I've tried 3 different sites, including building a fresh one). So I need more info:
1. what php version are you on?
2. are you seeing errors in the log?
3. what happens when you click the 'Apply Default Tripal Layout (will reset current layout)" button in manage display?
4. do you have any site specific functions that are targeting the content type fields/display? 

Thanks in advance!

**Comment by laceysanderson** [comment]
Hmmmm.... that's weird. It's seems highly repeatable on my system. I've been doing a lot of testing that requires a full site re-install and every time I'm seeing this issue. I've also seen it on my KnowPulse upgrade test site and my generic Tripal upgrade site (also no custom extensions).

- PHP Version: 5.6.7-1
- There are no errors in either the Drupal or Apache logs; nor did I see any when I prepared the site.
- This fixes it 👍  Both moves all the TripalPanes into the right column and orders them alphabetically.
- No site-specific functionality at all. I was testing chado views on a clean Tripal install with no extension modules installed.

I also just tested (on the same clean Tripal3 install) whether I see this when a new Tripal Content Type is added and I don't. So it seems to be restricted to the automatically created Tripal Content Types (created when the site is prepared).

**Comment by shawnawsu** [comment]
@laceysanderson Thanks for the additional info! I spoke with Stephen about it and he's run into similar problems but found a cache clear usually sorted things out. So I dropped a cache clear at the end of the function. Can you test to see if that helps with the problem? I am not able to reproduce the problem but I'm also running php 7.1.1 and wondering if that might be a reason I am seeing different behavior.

**Comment by shawnawsu** [comment]
I found the problem when I stood up another new site today. Line 137 of the tripal_ds.ds.inc file has this call: '    $all_field_groups = field_group_info_groups('TripalEntity', $bundle_name); '. It is returning nothing. I'm not entirely sure why, as the hook_bundle_postcreate is called after tripal_create_bundle_fields so the fields should be there. What does pull in info is field_info_instances so I am going make a few tweaks that should fix this.

**Comment by shawnawsu** [comment]
This is fixed in the latest 7.x-3.x-dashboard branch. I've tested it extensively but if anyone else wants to have a test that would be fine by me!

**Comment by laceysanderson** [comment]
@shawnawsu I'm still experiencing this on freshly created Tripal3 site (built just this morning using fff99517). Did these changes ever make it into core?

My Current Environment:

- Ubuntu 14.04.5 LTS (trusty)
- Apache 2.4.7
- PHP 5.5.9
- PostgreSQL 9.3.15
- Drupal 7.55
- Drush 8.1.12
- PHP-daemon Library v2.0
- Tripal 3.x Development branch (fff99517)
- No custom modules

Clicking "Apply default Layout" still fixes the problem but it's very confusing to publish content and then go look at it only to see nothing but a table of contents that doesn't work...

**Comment by spficklin** [comment]
We may have forgotten to merge in fixes for this from a branch where the fix was applied. We have merged all of those fixes now.  Can you try and see if this is resolved now?

**Comment by laceysanderson** [comment]
Sorry guys... I just built a new site (commit de232a94) and 5 out of 7 default content types are showing this behaviour...

**Comment by shawnawsu** [comment]
Ok, I found the problem. When I was cleaning up the branch I commented something back in that I shouldn't have. I have tested this 2 times, by standing up new sites, and it's working for me. Please do test.

**Comment by laceysanderson** [comment]
I can confirm it's fixed for me in your 7.x-3.x-dashboard branch :-) 

I'm going to leave the issue open until it's been merged back into 7.x-3.x and tested one last time --just so we don't forget ;-)

**Comment by laceysanderson** [comment]
The fix is in the main branch and tested 👍
