### ISSUE TITLE
Cannot create new publication

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#127]
When I try to create a publication, I receive the following error:
> Could not save the entity: SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "type_id" violates not-null constraint DETAIL: Failing row contains (4, Cryopreservation of nucellar cells of navel orange (Citrus sinen..., null, 9, null, 1, 1990, 30-33, null, 10.1007/BF00232130, null, f, null, null).

My Test Entity:

> Title: Cryopreservation of nucellar cells of navel orange (Citrus sinensis Osb. var. brasiliensis Tanaka) by vitrification
> Volume: 9
> Issue: 1
> Pyear: 1990
> Pages: 30-33
> Identifier: 10.1007/BF00232130
> Journal Abbreviation: Plant Cell Reports
> Authors: A. Sakai, S. Kobayashi, I. Oiyama
> Citation: Sakai, A., Kobayashi, S. & Oiyama, I. Plant Cell Reports (1990) 9: 30. doi:10.1007/BF00232130
> Abstract: The nucellar cells of navel orange(Citrus sinensis Osb. var. brasiliensis Tanaka) were successfully cryopreserved by vitrification. In this method, cells were sufficiently dehydrated with highly concentrated cryoprotective solution(PVS2) prior to direct plunge in liquid nitrogen. The PVS2 contains(w/v) 30% glycerol, 15% ethylene glycol and 15% DMSO in Murashige-Tucker medium(MT) containing 0.15 M sucrose. Cells were treated with 60% PVS2 at 25°C for 5 min and then chilled PVS2 at 0°C for 3 min. The cell suspension of about 0.1 ml was loaded in a 0.5 ml transparent plastic straw and directly plunged in liquid nitrogen for 30 min. After rapid warming, the cell suspension was expelled in 2 ml of MT medium containing 1.2 M sucrose. The average rate of survival was about 80%. The vitrified cells regenerated plantlets. This method is very simple and the time required for cryopreservation is only about 10 min.
> DOI: 10.1007/BF00232130
> **Publication Type: Article**

The Publication Type is showing up as a non-required textarea 👎  when I would expect a required drop-down...

**Comment by spficklin** [comment]
Okay. I'll look into it.

**Comment by spficklin** [comment]
This is now fixed with the latest commit.  You'll need to run a 'drush updatedb' for some necessary fixes.

**Comment by spficklin** [comment]
I'll wait to close this until you can test it on your end.

**Comment by laceysanderson** [comment]
This is still not working for me. 

I tried:
1. Using my existing site, pulling code changes, running updatedb and clearing the cache excessively.
2. Creating an entirely new Tripal 3 site.
Both resulted in similar behaviour...

What I see: Now I see a "Publication Type" dropdown 👍  however, it has no terms 👎  so I can't select a type and it's still not required 👎 .

**Comment by spficklin** [comment]
One of the updatedb functions was supposed to run the cvtermpath table on the tripal_pub vocabulary.   If you see no publication types that's why.  Did you have any problems running the updatedb?    Also, I think the problem is we must have commented out the code to run the cvtermpath after importing OBOs.  We need to add that back in.  But @shawnawsu has a fix for the GO problem and we have a completely new cvtermpath function in PHP to deal with loops.   

Can you see why the updatedb didn't run? I'ts number 7312 in the tripal_chado install file.

**Comment by laceysanderson** [comment]
Unfortunately the old site no longer exists but I specifically remember running the updatedb and it saying updating the cvtermpath without errors...

Anyway, I just checked by running the code inside the update hook in my fresh tripal site and as promised it fixed the emptiness of the drop-down :-)
```php
    $cv = tripal_get_cv(array('name' => 'tripal_pub'));
    tripal_update_cvtermpath($cv->cv_id);
    $cv = tripal_get_cv(array('name' => 'tripal_contact'));
    tripal_update_cvtermpath($cv->cv_id);
```
Furthermore, once I was able to select a type, I was also able to create a publication.

**Updating the cvtermpath definitely needs to be added back to the prepare chado function before release ;-)**

**Comment by spficklin** [comment]
Great!  I'm going to close out this issue then.  I'm testing Shawna's fix for the cvtermpath problem and if all goes well we'll replace the old PgPLsql call with the new PHP version.
