### ISSUE TITLE
Issue Creating Map Content Type 

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#204]
When creating a content type using the featuremap table there is no type_id column.  This throws off the form. It doesn't automatically provide the ability to use the featuremapprop table.  The user is forced to selected the unittype_id field, then select '--None--' to get the property elements to appear.

**Comment by laceysanderson** [comment]
This is fixed as we now have a map content type on install.

**Comment by spficklin** [comment]
This unfortunately is still a problem.   We have the map type created on install, but if someone deletes it and wants to recreate it manually they cannot :-(

**Comment by spficklin** [comment]
This should be fixed before stable release.

**Comment by spficklin** [comment]
PR merged! closing.
