### ISSUE TITLE
local__is_obsolete field widget prevents creation

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#255]
## Description of issue

Cannot manually create libraries, because of the local__is_obsolete field.

## Recreating this issue
a) Migrate a library content type to Tripal 3.  In my case I migrated BAC libraries
b) the local__is_obsolete field will be attached by default
c) Adding to manually create new libraries results in an error
d) The "Is obsolete" box is required but I couldn't find a value that allowed submission.  I tried 0, 1, "obsolete" and "current" 

## Resolving this issue
I changed the widget from free Text to Boolean.  It no longer showed up and allowed manual creation.

## Additional discussion
* this is a column in my base table (despite the docs not listing it, i guess they are out of date http://gmod.org/wiki/Chado_Library_Module)
* we should consider creating tripal 3 bundles for all base tables that at least the migrator will create.  And then see if we can manually create that content.  Any bogus field will be sussed out pretty quickly.

**Comment by spficklin** [comment]
So, I found a bug in the code that prevented the local__is_obsolete or any other checkbox from being shown as a widget when editing a form.  I've committed a fix.  Can you see if that resolves your problem?

**Comment by bradfordcondon** [comment]
Hi Stephen: it doenst show up as a checkbox but as a free text box.  However, now I can create or edit it by submitting 0 or 1.

I tried changing the widget but it still shows up as a free text box after picking, say, single on/off checkbox.  Not sure whats going on here.

**Comment by spficklin** [comment]
i see what's wrong.  In the feature table the column is_obsolete is boolean but in the library table it's an integer that throws off the field generation.  I've fixed this by forcing all is_obsolete fields to be boolean.  You should be able to remove the is_obsolete field from your library content types and click the "Check for new fields" on the content type page.  This should re-add the field as a boolean and you'll have the checkbox .

**Comment by bradfordcondon** [comment]
Hi Stephen:

pulled to test and site breaks with this error

```

Undefined table: 7 ERROR:  relation "chado.db2cv_mview" does not exist
LINE 1: ..., &#039;) as name     FROM chado.db DB      INNER JOIN chado.db2c...
                                                             ^:      SELECT DB.name as short_name, DB.description, DB.url, DB.urlprefix,       array_to_string(array_agg(DBCVM.cvname), &#039;, &#039;) as name     FROM chado.db DB      INNER JOIN chado.db2cv_mview DBCVM ON DBCVM.db_id = DB.db_id     WHERE DB.name = :name     GROUP BY DB.name, DB.description, DB.url, DB.urlprefix  ; Array
(
    [:name] => hydra
)
 in chado_query() (line 1680 of /Users/chet/UTK/tripal/sites/all/modules/tripal/tripal_chado/api/tripal_chado.query.api.inc).

```

**Comment by spficklin** [comment]
Hi @bradfordcondon you'll have to run a 'drush updatedb' on the most recent update.  That should fix the problem.

**Comment by bradfordcondon** [comment]
duh of course

Great, we've got a checkbox now.  thanks!
