### ISSUE TITLE
PDO exception on user file area

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#456]
### System information

* Tripal Version:3

### Issue description

When investigating an error report on our admin account (user's data is not writable: !user_dir) I went to the user files tab.  I was unable to visit the page because of the below PDO error.

#### Steps to reproduce
I'm not sure unfortunately. I get this error on my live site, not my personal site.

#### Error messages and screenshots

```
PDOException: SQLSTATE[42803]: Grouping error: 7 ERROR: column "fm.filename" must appear in the GROUP BY clause or be used in an aggregate function LINE 2: SELECT FM.fid, FM.filename, TGEF.expiration_date ^: SELECT FM.fid, FM.filename, TGEF.expiration_date FROM {file_managed} FM INNER JOIN {file_usage} FU on FM.fid = FU.fid and FM.uid = :user_id LEFT JOIN {tripal_expiration_files} TGEF on TGEF.fid = FU.fid WHERE FU.module = 'tripal' GROUP BY FM.fid, TGEF.expiration_date ORDER BY FM.filename ; Array ( [:user_id] => 1 ) in tripal_user_files_page() (line 27 of /var/www/html/sites/all/modules/tripal/tripal/includes/tripal.user.inc).
```

Here is the linked code:

https://github.com/tripal/tripal/blob/48e1a690cf68b224547e8d8d3027144d2b10f7dc/tripal/includes/tripal.user.inc#L13-L27

As per the error, adding FM.filename to the GROUP BY clause resolves the error.

edit: Im not sure it resolves the error.  It allows me to visit the page ,but shows no files. This is despite there being 100mb of space used.  This number is also wrong, since checking the files we have ~1gb for that user.

**Comment by almasaeed2010** [comment]
I think the Group By statement here is a mistake since group by is used with aggregate functions and this query doesn't have one. I'd try removing it and looking at the results again. 

If the intention here is to get unique file ids, I'd use DISTINCT(FM.fid).

Thanks!

**Comment by spficklin** [comment]
I do not get an error when I visit the user uploads page on my site.  But @almasaeed2010 is correct that the group by shouldn't be there.  Odd that I don't get an error but you do.  I committed a fix to this branch, can you test:  456-tv3-user_files_issue

**Comment by bradfordcondon** [comment]
* confirmed that no problem on my dev site on current master.  Issue is specific to our live site for some reason.
* confirmed that error still occurs on **master** branch of live
* confirmed that @spficklin 's branch `456-tv3-user_files_issue` resolves issue on live.

**Comment by bradfordcondon** [comment]
ps: I know its not the main issue of this thread, but your branch does not resolve the discrepancy between the uploaded files and the usage.  Maybe this discrepancy makes sense for some reason?

Note usage is 8gb, only 1 file is listed at 263mb
![screen shot 2018-06-26 at 11 15 15 am](https://user-images.githubusercontent.com/7063154/41922066-4c4291f4-7932-11e8-9a95-d5cd230368c4.png)

**Comment by spficklin** [comment]
My total is correct so I can't reproduce the problem.  But I did make some adjustments to the code that might fix it for you.  I've also issued a PR for this.

**Comment by bradfordcondon** [comment]
![screen shot 2018-06-28 at 7 59 30 am](https://user-images.githubusercontent.com/7063154/42033038-8bf42678-7aa9-11e8-9f4c-faa4b770e2c1.png)

Resolved!  Thank you @spficklin .
